### ISSUE TITLE
Fix the dataset mount script in ScriptRunConfig

### ISSUE THREAD

**Issue by classicboyir** [Azure/MachineLearningNotebooks#1222]
Passing a dataset.as_mount() to ScriptRunConfig the way provided in this page raises the `TypeError: Object of type 'DataReference' is not JSON serializable` exception. Instead, the script should add one more step to make it serializable in the ScriptRunConfig as elaborated in this stackoverflow [response](https://stackoverflow.com/questions/58019308/scriptrunconfig-with-datastore-reference-on-aml)

Here is the change that needs to be applied prior to calling the as_mount function:
arguments=['--input-data-dir', dataset.as_named_input('input').as_mount()]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b080f459-b191-a60e-e327-720ef095165c
* Version Independent ID: 53d1b412-0c47-1044-3c6c-7c8c0f1eb0c0
* Content: [azureml.data.FileDataset class - Azure Machine Learning Python](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.data.filedataset?view=azure-ml-py)
* Content Source: [AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.FileDataset.yml](https://github.com/MicrosoftDocs/MachineLearning-Python-pr/blob/live/AzureML-Docset/stable/docs-ref-autogen/azureml-core/azureml.data.FileDataset.yml)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @debfro
* Microsoft Alias: **debfro**

**Comment by MayMSFT** [comment]
Hi @classicboyir 

dataset.as_mount() should work now by upgrading to the latest SDK version. Can you help confirm?

Thanks

**Comment by krishansubudhi** [comment]
It still does not work.
azureml core version'1.2.0'

TypeError: Object of type DataReference is not JSON serializable

This thing was perfectly working while I was using estimators. why did you move to ScriptRunConfig and break the behaviour?

**Comment by lostmygithubaccount** [comment]
1.2.0 is very old, the current version is 1.18.0 and new versions are released every other week

The recommendation is to use a `Dataset.File.from_*` and a `ScriptRunConfig` rather than a DataReference or other method

**Comment by krishansubudhi** [comment]
Upgrading worked. But datasets only support read only files. How do I mount a writable storage location? Example scenario : output periodic checkpoint from a long running training job.

**Comment by lostmygithubaccount** [comment]
I believe @mx-iao and @aminsaied are building a best practices checkpointing example over at https://github.com/Azure/azureml-examples 

@MayMSFT what is the recommendation for writable mount? Use blobfuse directly? Datasets?

**Comment by MayMSFT** [comment]
Hi @krishansubudhi  you can configure dataset as output to your scriptrun. sample notebook here: https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/work-with-data/datasets-tutorial/pipeline-with-datasets/pipeline-for-image-classification.ipynb

**Comment by meyetman** [comment]
Should you still have questions regarding this issue, please comment here and reopen it. We're closing it for now. #please-close
