### ISSUE TITLE
01.train-within-notebook.pynb: error on Webservice.deploy_from_model()

### ISSUE THREAD

**Issue by nansravn** [Azure/MachineLearningNotebooks#27]
I've successfully executed the `00.configuration.ipynb` notebook, but when I try to execute the `01.train-within-notebook.ipynb`, I get an error message when I'm trying to execute the following cell:

```
%%time
# this will take 5-10 minutes to finish
# you can also use "az container list" command to find the ACI being deployed
service = Webservice.deploy_from_model(name='myacisvcwbapsv',
                                       deployment_config=aciconfig,
                                       models=[model],
                                       image_config=image_config,
                                       workspace=ws)

service.wait_for_deployment(show_output=True)
```

**Output:**
```
Creating image
Image creation operation finished for image acirandomname:1, operation "Failed"
Image creation failed with
StatusCode: 400
Message: Docker Build Failed
---------------------------------------------------------------------------
WebserviceException                       Traceback (most recent call last)
<timed exec> in <module>()

~/anaconda2/envs/aml36/lib/python3.6/site-packages/azureml/core/webservice/webservice.py in deploy_from_model(workspace, name, models, image_config, deployment_config, deployment_target)
    251         image.wait_for_creation()
    252         if image.creation_state != 'Succeeded':
--> 253             raise WebserviceException('Error occurred creating image {} for service.'.format(image.id))
    254         return Webservice.deploy_from_image(workspace, name, image, deployment_config, deployment_target)
    255 

WebserviceException: Error occurred creating image acirandomname:1 for service.
```

I've already tried to execute this code on Azure Notebooks and also locally (I've created a new conda env for this deployment and installed all the AML dependencies).

**The same error appears on both of these environments.**

**Comment by rastala** [comment]
Thank you for reporting! There's an ongoing issue with image creation engine, team is investigating.

**Comment by rastala** [comment]
This is an issue with an update to one of package dependencies. The workaround is to add pynacl 1.2.1 explicitly as dependency:

myenv = CondaDependencies()
myenv.add_pip_package("pynacl==1.2.1")

**Comment by rastala** [comment]
This issue has been resolved, the web service deployment should work without pinned pynacl now.

**Comment by Jerrybonheur** [comment]
I've a same issue as nansravn's. I added: 
myenv = CondaDependencies()
myenv.add_pip_package("pynacl==1.2.1")
But it still doesn't work
